### ISSUE TITLE
App bleibt schwarz

### ISSUE THREAD

**Issue by LukiLeu** [mopsalarm/Pr0#119]
Bei mir passiert es immer wieder, dass die App nach ein paar Starts einfach schwarz bleibt. Ich muss dann immer den Cache und die Daten der App in den Einstellungen löschen gehen, dann startet die App wieder normal.

**Comment by mopsalarm** [comment]
Bitte logcat anfertigen von einem Start, wo die App schwarz bleibt, sonst kann ich nichts machen.

**Comment by LukiLeu** [comment]
Das einzige was erscheint ist: "Initalize Fabric". Anschliessend nichts mehr.

**Comment by mopsalarm** [comment]
Wenn die App normal startet, kommen dann mehr logausgaben?
Sehr seltsam jedenfall. Custom Rom oder Stock?

**Comment by LukiLeu** [comment]
Wenn die App normal startet, kommt ebenfalls nur diese Meldung (wenn ich nach Pr0grammApplication filtere). Wenn ich nur nach Pr0gramm filtere kommen noch mehr (ich habe oben dummerweise nach Pr0grammApplication gefiltert. Ich werde das nächste Mal wenn die App nicht mehr startet einmal nur nach Pr0gramm filtern.
Ich habe ein HTC One M9 - Stock ROM - Android 5.1

**Comment by mopsalarm** [comment]
Nein, filter weder nach Pr0gramm noch nach Pr0grammApplication. Das wird dir nicht viel bringen. Es gibt keinen gemeinsamen logprefix. Probiere das also nochmal, wenn die App nicht mehr startet.

**Comment by LukiLeu** [comment]
[2016-01-07-21-43-17.txt](https://github.com/mopsalarm/Pr0/files/81739/2016-01-07-21-43-17.txt)
Hier ist ein logcat file, bei welchem die App nicht gestartet ist (resp. schwarz blieb). Ich hoffe dies hilft dir weiter.

**Comment by schr3j** [comment]
Eventuell hier?
```
01-07 21:43:48.121 E/Fabric  (31094): Unknown error while loading Crashlytics settings. Crashes will be cached until settings can be retrieved.
01-07 21:43:48.121 E/Fabric  (31094): djh: java.net.ConnectException: failed to connect to settings.crashlytics.com/127.0.0.1 (port 443) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
01-07 21:43:48.121 E/Fabric  (31094): 	at djc.b(Unknown Source)
01-07 21:43:48.121 E/Fabric  (31094): 	at djy.a(Unknown Source)
01-07 21:43:48.121 E/Fabric  (31094): 	at dkh.a(Unknown Source)
01-07 21:43:48.121 E/Fabric  (31094): 	at dkd.b(Unknown Source)
01-07 21:43:48.121 E/Fabric  (31094): 	at dgd.f(Unknown Source)
01-07 21:43:48.121 E/Fabric  (31094): 	at dgd.c(Unknown Source)
01-07 21:43:48.121 E/Fabric  (31094): 	at dgd.e(Unknown Source)
01-07 21:43:48.121 E/Fabric  (31094): 	at dfy.a(Unknown Source)
01-07 21:43:48.121 E/Fabric  (31094): 	at dhn.call(Unknown Source)
01-07 21:43:48.121 E/Fabric  (31094): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-07 21:43:48.121 E/Fabric  (31094): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
01-07 21:43:48.121 E/Fabric  (31094): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-07 21:43:48.121 E/Fabric  (31094): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-07 21:43:48.121 E/Fabric  (31094): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-07 21:43:48.121 E/Fabric  (31094): 	at java.lang.Thread.run(Thread.java:818)
01-07 21:43:48.121 E/Fabric  (31094): Caused by: java.net.ConnectException: failed to connect to settings.crashlytics.com/127.0.0.1 (port 443) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
01-07 21:43:48.121 E/Fabric  (31094): 	at libcore.io.IoBridge.isConnected(IoBridge.java:238)
01-07 21:43:48.121 E/Fabric  (31094): 	at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
01-07 21:43:48.121 E/Fabric  (31094): 	at libcore.io.IoBridge.connect(IoBridge.java:122)
01-07 21:43:48.121 E/Fabric  (31094): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
01-07 21:43:48.121 E/Fabric  (31094): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
01-07 21:43:48.121 E/Fabric  (31094): 	at java.net.Socket.connect(Socket.java:882)
01-07 21:43:48.121 E/Fabric  (31094): 	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:174)
01-07 21:43:48.121 E/Fabric  (31094): 	at com.android.okhttp.Connection.connect(Connection.java:152)
01-07 21:43:48.121 E/Fabric  (31094): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
01-07 21:43:48.121 E/Fabric  (31094): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
01-07 21:43:48.121 E/Fabric  (31094): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:403)
01-07 21:43:48.121 E/Fabric  (31094): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:353)
01-07 21:43:48.121 E/Fabric  (31094): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:540)
01-07 21:43:48.121 E/Fabric  (31094): 	at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
01-07 21:43:48.121 E/Fabric  (31094): 	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
01-07 21:43:48.121 E/Fabric  (31094): 	... 15 more
01-07 21:43:48.121 E/Fabric  (31094): Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
01-07 21:43:48.121 E/Fabric  (31094): 	at libcore.io.IoBridge.isConnected(IoBridge.java:223)
01-07 21:43:48.121 E/Fabric  (31094): 	... 29 more
01-07 21:43:48.121 E/Answers (31094): Failed to retrieve settings
01-07 21:43:48.141 W/CrashlyticsCore(31094): Received null settings, skipping initialization!
01-07 21:43:48.521 D/PMS     ( 1142): releaseHCC(a28339d): CPU_MIN_NUM ActivityManager-MultiCore-Num 0x8000 null
01-07 21:43:48.521 D/PMS     ( 1142): releaseHCC(1b460012): CPU_MIN_FREQ ActivityManager-MultiCore-Freq 0x2000 null
01-07 21:43:48.561 D/HtcThemeUtils( 3571): Clear the texture cache.
01-07 21:43:48.561 D/HtcThemeUtils( 3571): java.lang.Throwable
01-07 21:43:48.561 D/HtcThemeUtils( 3571): 	at com.htc.lib1.cc.util.HtcThemeUtils.clearCaches(HtcThemeUtils.java:417)
01-07 21:43:48.561 D/HtcThemeUtils( 3571): 	at com.htc.lib1.cc.util.HtcCommonUtil.clearCache(HtcCommonUtil.java:558)
01-07 21:43:48.561 D/HtcThemeUtils( 3571): 	at com.android.systemui.HWMemoryController$1.run(HWMemoryController.java:87)
01-07 21:43:48.561 D/HtcThemeUtils( 3571): 	at android.os.Handler.handleCallback(Handler.java:739)
01-07 21:43:48.561 D/HtcThemeUtils( 3571): 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-07 21:43:48.561 D/HtcThemeUtils( 3571): 	at android.os.Looper.loop(Looper.java:155)
01-07 21:43:48.561 D/HtcThemeUtils( 3571): 	at android.app.ActivityThread.main(ActivityThread.java:5725)
01-07 21:43:48.561 D/HtcThemeUtils( 3571): 	at java.lang.reflect.Method.invoke(Native Method)
01-07 21:43:48.561 D/HtcThemeUtils( 3571): 	at java.lang.reflect.Method.invoke(Method.java:372)
01-07 21:43:48.561 D/HtcThemeUtils( 3571): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1030)
01-07 21:43:48.561 D/HtcThemeUtils( 3571): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)
01-07 21:43:48.571 D/HtcUPManager( 3571): HtcUPServiceProxy onTrimMemory() has been called. Memory Level: 60
01-07 21:43:48.571 D/HtcUPManager( 3571): HtcUPServiceProxy onTrimMemory() has been called. Memory Level: 60
01-07 21:43:49.691 D/HtcWifiControlRoamOffload: ( 1142): Receive mPhoneStateListener
01-07 21:43:49.691 D/HtcWifiControlRoamOffload: ( 1142): Receive mPhoneStateListener, getGsmSignalStrength99
01-07 21:43:49.701 D/TelephonyCallback( 3571): SignalStrength: 2
01-07 21:43:49.721 D/SIGNAL_ICON( 3571): level=2/5

```

**Comment by pr0user** [comment]
besitze auch das HTC one M9 und habe den gleichen Fehler.
Android 5.1
HTC Sence 7.0
Software Nummer 2.10.206.2

Denke mal es liegt an HTC / Sence, ich schau mal ob ich etwas in erfahrung bringen kann

**Comment by mopsalarm** [comment]
Also der Stacktrace oben kommt davon, wenn Crashlytics/Frabric von Adaway oder einem ähnlichen Werbeblocker geblockt wird. Das sollte aber kein Problem sein, das habe ich auf meinem Gerät auch, und die App läuft wunderbar. Was mir mehr sorgen macht, ist
`01-07 21:43:47.981 W/HttpModule(31094): Stop trying, using no proxy now.`
Hast du irgendeine Art "Firewall" installiert? Es wird der App scheinibar verboten, ein Socket zu öffnen.

Das allerdings sollte aber ebenfalls nicht dazu führen, dass die App nicht funktioniert.

**Comment by LukiLeu** [comment]
[2016-01-09-17-47-52.txt](https://github.com/mopsalarm/Pr0/files/83757/2016-01-09-17-47-52.txt)
Hier noch ein Logfile wenn es startet. Firewall habe ich keine installiert. Nur Adaway welche Werbung blockt.

**Comment by mopsalarm** [comment]
Ursache immer noch unbekannt.

**Comment by LukiLeu** [comment]
Ich habe jetzt einmal auf Android 6 aktualisiert. mal schauen ob das Problem hier auch auftritt

**Comment by IchbinkeinReh** [comment]
Hallo,
hatte das problem auch schon ein paar mal. Nur cache löschen hilft. 

Die Ursache des Problems ist das Preloading. Ich konnte das Problem reproduzieren indem ich etwas preloade und dann die app nach ca einem tag wieder öffne. Ich hab ein Samsung S4 mini mit Android 4.4.2.

Scheint ein Deadlock zu sein. Hier ist ein thread report (App als Debug compiliert):
http://pastebin.com/AmMjysuJ
und hier ist das logcat:
http://pastebin.com/5REpbYN7

**Comment by mopsalarm** [comment]
Das klingt jetzt mal richtig hilfreich. Danke, gucke ich mir nachher mal an. Dann gibt's heute noch nen fix

**Comment by schr3j** [comment]
@mopsalarm falls du das nicht weißt: Wenn du als commit message "fix #119" schreibst wird das issue automatisch geschlossen ;)

**Comment by mopsalarm** [comment]
:+1:
