### ISSUE TITLE
App stürzt bei fehlenden Google Diensten ab

### ISSUE THREAD

**Issue by liquidsky** [mopsalarm/Pr0#174]
Bei LineageOS 15.1 ohne GApps lässt sich die APP nicht mehr starten bzw. stürzt bereits nach einer Sekunde ab.

FATAL EXCEPTION: pool-3-thread-1
Process: com.pr0gramm.app, PID: 12754
java.lang.SecurityException: Failed to find provider com.google.android.gsf.gservices for user 0; expected to find a valid ContentProvider for this authority
	at android.os.Parcel.readException(Parcel.java:2004)
	at android.os.Parcel.readException(Parcel.java:1950)
	at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:768)
	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1924)
	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1913)
	at dnc.a(Unknown Source:38)
	at dth.<init>(Unknown Source:145)
	at dsx.a(Unknown Source:124)
	at dsy.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

**Comment by mopsalarm** [comment]
Danke für den Hinweis. Das wundert mich ein wenig, da ich oft im Emulator ohne PlayServices teste. Schaue ich demnächst mal rein.

**Comment by liquidsky** [comment]
Um es etwas einzukreisen. Version 1.141.5 funktioniert noch, ab 1.142.1 nicht mehr.

**Comment by MeikelLP** [comment]
Kann ich bestätigen. Seit dem upgrade 14.1 -> 15.1 ist die APP komplett broken bei mir.

**Comment by lutobler** [comment]
Kann ich auch auf Copperhead OS (Android 8.1.0, keine Google Services) bestätigen, Version 1.143.0 stürzt direkt nach dem Start ab.

**Comment by mopsalarm** [comment]
Meh okay. Ich schaue mal, aber ich gebe keine Garantie.

**Comment by frtwnglr** [comment]
Ebenfalls LinageOS 15.1 (Android 8.1) ohne Google Dienste, kann das Problem mit identischer Fehlermeldung bestätigen.

**Comment by mopsalarm** [comment]
Probiert doch bitte mal die aktuelle Beta aus und erzählt mir, ob es jetzt funktioniert:
https://apk.pr0gramm.com/pr0gramm-1.143.1.apk

**Comment by frtwnglr** [comment]
Leider genau das Gleiche wie vorher. :/

FATAL EXCEPTION: pool-4-thread-1
Process: com.pr0gramm.app, PID: 8577
java.lang.SecurityException: Failed to find provider com.google.android.gsf.gservices for user 0; expected to find a valid ContentProvider for this authority
	at android.os.Parcel.readException(Parcel.java:2004)
	at android.os.Parcel.readException(Parcel.java:1950)
	at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:768)
	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1924)
	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1913)
	at dnc.a(Unknown Source:38)
	at dth.<init>(Unknown Source:145)
	at dsx.a(Unknown Source:124)
	at dsy.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

**Comment by mopsalarm** [comment]
Sollte nun in der aktuellen beta gehen.

**Comment by lutobler** [comment]
Funktioniert wieder, danke :+1:

**Comment by frtwnglr** [comment]
Ist die "aktuelle Beta": https://apk.pr0gramm.com/pr0gramm-1.143.1.apk ?

Die wirft bei mir nämlich immer noch den gleichen Fehler. Falls nicht, bitte einmal den Link für Dumme. ^^

**Comment by lutobler** [comment]
Ich nehme ann dass ist der Release: https://github.com/mopsalarm/Pr0/releases/tag/1.144.0
