### ISSUE TITLE
App crasht bei gelöschten Posts.

### ISSUE THREAD

**Issue by mist** [mopsalarm/Pr0#176]
Alte Posts, die in der Suche erscheinen, aber gelöscht sind, bringen die app zum crash.
Früher kam die Meldung dass der Post gelöscht wurde, mittlerweile (1.143) crasht sie direkt.

Ich gucke mal, ob ich noch einen log finden kann.

Leider kann ich keinen Beispielpost angeben, da es instant crasht, selbst wenn ich mir nur die Nachbarn angucke.

**Comment by mopsalarm** [comment]
Kannst du sagen wie man zu so einem Post kommt? Sowas wie "in A nach B suchen und dann der Post mit dem Hund - das fünfte Thumbnail" oder so?

**Comment by mist** [comment]
Hab dir eine PM geschrieben.
Das eine Problem ist wohl, dass die regexsuche Bilder liefert, die auf der HP nicht mehr vorhanden sind.

```
06-10 22:25:03.862 22108 22108 E AndroidRuntime: FATAL EXCEPTION: main
06-10 22:25:03.862 22108 22108 E AndroidRuntime: Process: com.pr0gramm.app, PID: 22108
06-10 22:25:03.862 22108 22108 E AndroidRuntime: java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at gcn$b.run(Unknown Source)
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6780)
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
06-10 22:25:03.862 22108 22108 E AndroidRuntime: Caused by: rx.exceptions.OnErrorNotImplementedException: Bitmap is not valid
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at ggb$c.call(Unknown Source)
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at gfy.a(Unknown Source)
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at gif.a(Unknown Source)
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at gig.a(Unknown Source)
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at gih.a(Unknown Source)
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at gey$1.a(Unknown Source)
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at gem$a.a(Unknown Source)
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at gem$a.a(Unknown Source)
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        ... 8 more
06-10 22:25:03.862 22108 22108 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Bitmap is not valid
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at kn$a.<init>(Unknown Source)
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at esy$bb.call(Unknown Source)
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at gdo.call(Unknown Source)
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at gcb.a(Unknown Source)
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at gev$a.a(Unknown Source)
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at gfj$b$1.a(Unknown Source)
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at gfp.run(Unknown Source)
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
06-10 22:25:03.862 22108 22108 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:762)
06-10 22:25:03.902  1425 14889 W ActivityManager:   Force finishing activity com.pr0gramm.app/.ui.MainActivity
06-10 22:25:04.060  1425  1524 D WindowManager: openInputChannel mInputChannel: 9234e60 Application Error: com.pr0gramm.app (server)
06-10 22:25:04.076  1425  1524 V WindowManager: Relayout Window{9234e60d0 u0 Application Error: com.pr0gramm.app}: viewVisibility=0 req=1023x300 WM.LayoutParams{(0,0)(wrapxwrap) gr=#11 sim=#120 ty=2003 fl=#1820002 pfl=0x110 fmt=-3 wanim=0x103038b surfaceInsets=Rect(4, 4 - 4, 4) needsMenuKey=2 naviIconColor=0}
06-10 22:25:04.136  1425  1524 D WindowManager: finishDrawingWindow: Window{9234e60d0 u0 Application Error: com.pr0gramm.app} mDrawState=DRAW_PENDING
06-10 22:25:04.142  1425  1524 D WindowManager: finishDrawingWindow: Window{9234e60d0 u0 Application Error: com.pr0gramm.app} mDrawState=HAS_DRAWN
06-10 22:25:04.464  1425  1523 W ActivityManager: Activity pause timeout for ActivityRecord{29e7415d0 u0 com.pr0gramm.app/.ui.MainActivity t14666 f}
06-10 22:25:04.465  1425  1523 D ActivityManager: resumeTopActivityInnerLocked() : #0 prevTask=TaskRecord{cff3c91d0 #14666 A=com.pr0gramm.app U=0 StackId=1 sz=1} next=ActivityRecord{b42ad1dd0 u0 com.teslacoilsw.launcher/.NovaLauncher t14461} mFocusedStack=ActivityStack{d68a24dd0 stackId=0, 2 task
```

**Comment by mopsalarm** [comment]
"Bitmap is not valid" mit regex hat das nichts zu tun. Rx ist steht für reactive extensions, falls du das meinst.
Hier du auf der Beta von gestern Abend? Habe nämlich zu dem oben genannten Fehler bereits einen Fix gepusht.

**Comment by mist** [comment]
Nein, ich meine die Bildsuche, die mir eine `? ` beginnt.
Aber die neueste Version crasht nicht mehr, Problem gefixt.

**Comment by mopsalarm** [comment]
Das ist dann die "erweiterte Suche". 
Super, dann ist das Problem ja aus der Welt. Schöne Woche.

**Comment by mist** [comment]
Ja stimmt, sind keine regex, die könnten ja das, was ich an der Suche vermisse.
Ebenso!
