### ISSUE TITLE
Alpha Testing

### ISSUE THREAD

**Issue by mopsalarm** [mopsalarm/Pr0#90]
Moin Jungs, ich brauche mal eure Hilfe für einen Alpha-Test. Ich habe jetzt, nachdem der Videoplayer mit den Animationsumbauten aus der Recyclerview wieder aus ist, ein paar Tester, die gucken, ob Videos (nicht mit Softwaredecoder!) noch sauber funktionieren.

http://pr0.wibbly-wobbly.de/pr0-alpha-video.apk

@schr3j @Graphicscore @kratostav @MetalMatze 

Die Firma dankt.

**Comment by schr3j** [comment]
Ist grade ein Crash in der Play Dev Console reingeschwirrt. Sieht aus als würde er relatieren (hab nur irgendwas von Video gelesen...)

```
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:54)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
at java.util.concurrent.FutureTask.run(FutureTask.java:234)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:856)
Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:201)
at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:111)
at rx.internal.operators.OperatorSubscribeOn$1$1$1.onError(OperatorSubscribeOn.java:71)
at rx.util.async.operators.OperatorFromFunctionals$InvokeAsync.call(OperatorFromFunctionals.java:75)
at rx.util.async.operators.OperatorFromFunctionals$InvokeAsync.call(OperatorFromFunctionals.java:62)
at rx.Observable.unsafeSubscribe(Observable.java:7304)
at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47)
... 7 more
Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
at com.crashlytics.android.core.SessionDataWriter.getEventAppExecutionExceptionSize(SessionDataWriter.java:597)
at com.crashlytics.android.core.SessionDataWriter.getEventAppExecutionExceptionSize(SessionDataWriter.java:600)
at com.crashlytics.android.core.SessionDataWriter.getEventAppExecutionSize(SessionDataWriter.java:533)
at com.crashlytics.android.core.SessionDataWriter.getEventAppSize(SessionDataWriter.java:494)
at com.crashlytics.android.core.SessionDataWriter.getSessionEventSize(SessionDataWriter.java:473)
at com.crashlytics.android.core.SessionDataWriter.writeSessionEvent(SessionDataWriter.java:195)
at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.writeSessionEvent(CrashlyticsUncaughtExceptionHandler.java:959)
at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.writeFatal(CrashlyticsUncaughtExceptionHandler.java:394)
at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.handleUncaughtException(CrashlyticsUncaughtExceptionHandler.java:297)
at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.access$200(CrashlyticsUncaughtExceptionHandler.java:56)
at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler$7.call(CrashlyticsUncaughtExceptionHandler.java:277)
at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler$7.call(CrashlyticsUncaughtExceptionHandler.java:274)
at java.util.concurrent.FutureTask.run(FutureTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:75)
at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)
... 1 more
Caused by: java.lang.NullPointerException
at com.pr0gramm.app.ui.views.viewer.VideoMediaView.lambda$openMediaPlayer$206(VideoMediaView.java:292)
at com.pr0gramm.app.ui.views.viewer.VideoMediaView.access$lambda$1(VideoMediaView.java)
at com.pr0gramm.app.ui.views.viewer.VideoMediaView$$Lambda$2.call(Unknown Source)
at rx.util.async.operators.OperatorFromFunctionals$InvokeAsync.call(OperatorFromFunctionals.java:73)
at rx.util.async.operators.OperatorFromFunctionals$InvokeAsync.call(OperatorFromFunctionals.java:62)
at rx.Observable.unsafeSubscribe(Observable.java:7304)
at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
at java.util.concurrent.FutureTask.run(FutureTask.java:234)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
... 1 more
Caused by: java.lang.IllegalStateException: Must be called from the main thread.
at com.pr0gramm.app.AndroidUtility.checkMainThread(AndroidUtility.java:112)
at com.pr0gramm.app.ui.views.viewer.VideoMediaView.moveTo(VideoMediaView.java:90)
at com.pr0gramm.app.ui.views.viewer.VideoMediaView.lambda$openMediaPlayer$207(VideoMediaView.java:310)
at com.pr0gramm.app.ui.views.viewer.VideoMediaView.access$lambda$2(VideoMediaView.java)
at com.pr0gramm.app.ui.views.viewer.VideoMediaView$$Lambda$3.call(Unknown Source)
at rx.Observable$32.onError(Observable.java:7182)
at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:154)
at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:111)
at rx.internal.operators.OperatorSubscribeOn$1$1$1.onError(OperatorSubscribeOn.java:71)
at rx.util.async.operators.OperatorFromFunctionals$InvokeAsync.call(OperatorFromFunctionals.java:75)
... 11 more
```

**Comment by mopsalarm** [comment]
Ne. Habe die App nur hier gepostet. Wollte Feedback bevor ich sie als beta raus gebe
